### PR TITLE
Fix precompiler to work with Handlebars 2.0.0

### PR DESCRIPTION
**Pull request by simcha**
Added minor backward compatible changes to make barber-emblem work with new Handlebars.

### CODE REVIEW

**Comment by coladarci** [comment]
@machty - any chance you are free to weigh in on this pull? I'm very excited to try out htmlbars + ember-rails and this seems to be the final hold up! Thanks!

**Comment by Eric-Guo** [comment]
it works even for ember-source 1.8.1, really eager to see it can be release.

**Comment by danielspaniel** [comment]
@coladarci, have you been able to get this working? I am getting same issue with: 
`Compiler said: ReferenceError: Handlebars is not defined.` 
when using ember 1.10.0.beta3

**Comment by coladarci** [comment]
No I haven't but I think my issue is with emblem

**Comment by Eric-Guo** [comment]
@danielspaniel try `git clean -fd && git reset head`? maybe just cache in tmp?

**Comment by danielspaniel** [comment]
@Eric-Guo .. what are you talking about?  in which project do you mean ( to run git clean? ) ?? Do you mean rake assets:clobber or rake tmp:clear ??  puzzled

 My Gemfile looks like:

gem 'barber-emblem', git:'https://github.com/simcha/barber-emblem.git'
gem 'barber'
gem 'emblem-rails'
gem 'emblem-source', git:'https://github.com/machty/emblem.js.git' 
gem 'ember-source', '1.10.0.beta3'

what does your Gemfile look like?  Is it working then for you?

**Comment by machty** [comment]
Merged and published 0.1.2

**Comment by Eric-Guo** [comment]
@danielspaniel I means sometime the pre-compile will be cache, so may need to do clean first, anyway, I try the 1.10.0.beta4, emblem need master version since 0.3.18 not release [PR179](https://github.com/machty/emblem.js/pull/179) yet, but for 1.10, emblem is not ready, so highest version is 1.9.1.

``` ruby
source 'https://rubygems.org'

gem 'coffee-rails'
gem 'ember-rails'
gem 'ember-source', '~> 1.9.1'
gem 'emblem-rails'
gem 'emblem-source', github: 'machty/emblem.js'
gem 'faker'
gem 'haml-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'rails_12factor', group: :production
gem 'pg'
gem 'puma'
gem 'rails', '4.0.13'
gem 'sass-rails'
gem 'uglifier'
gem 'pry-rails'
```

**Pull request merged**
